"use strict";
const SUPPORTED=new Set(["en","uk","ru","fr","de","es","it","pt","nl","pl","cs","sk","hu","ro","bg","el","sv","da","no","fi","tr","ar","hi"]);
const NAMES={en:"English",uk:"Ukrainian",ru:"Russian",fr:"French",de:"German",es:"Spanish",it:"Italian",pt:"Portuguese",nl:"Dutch",pl:"Polish",cs:"Czech",sk:"Slovak",hu:"Hungarian",ro:"Romanian",bg:"Bulgarian",el:"Greek",sv:"Swedish",da:"Danish",no:"Norwegian",fi:"Finnish",tr:"Turkish",ar:"Arabic",hi:"Hindi"};
const MAX_ITEMS=100,MAX_TEXT=5000,MAX_TOTAL=30000,MODEL=process.env.OPENAI_MODEL||"gpt-4.1-mini";
function json(res,status,data){res.status(status).json(data)}
function validate(xs){if(!Array.isArray(xs))return"The texts field must be an array.";if(!xs.length)return"No text was provided.";if(xs.length>MAX_ITEMS)return`A maximum of ${MAX_ITEMS} text items is allowed.`;let total=0;for(const x of xs){if(typeof x!=="string")return"Every translation item must be text.";if(x.length>MAX_TEXT)return`One text item exceeds ${MAX_TEXT} characters.`;total+=x.length}return total>MAX_TOTAL?`The request exceeds ${MAX_TOTAL} characters.`:""}
function output(data){if(typeof data?.output_text==="string"&&data.output_text.trim())return data.output_text.trim();const p=[];for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==="output_text"&&typeof c.text==="string")p.push(c.text);return p.join("").trim()}
function parse(raw,n){const clean=String(raw||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const obj=JSON.parse(clean),xs=Array.isArray(obj)?obj:obj?.translations;if(!Array.isArray(xs)||xs.length!==n)throw new Error("The translation model returned an invalid response.");return xs.map(x=>String(x??""))}
module.exports=async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method==="GET")return json(res,200,{ok:true,endpoint:"/api/translate",method:"POST",languages:[...SUPPORTED]});if(req.method!=="POST"){res.setHeader("Allow","GET, POST");return json(res,405,{error:"Method not allowed."})}const key=process.env.OPENAI_API_KEY;if(!key)return json(res,500,{error:"OPENAI_API_KEY is not configured in Vercel."});const body=req.body||{},source=String(body.sourceLanguage||"en").toLowerCase(),target=String(body.targetLanguage||"").toLowerCase(),texts=body.texts;if(!SUPPORTED.has(source)||!SUPPORTED.has(target))return json(res,400,{error:"Unsupported language."});const error=validate(texts);if(error)return json(res,400,{error});if(source===target)return json(res,200,{translations:texts,targetLanguage:target});const instructions=[`Translate each item from ${NAMES[source]} to ${NAMES[target]}.`,`Return only valid JSON in this exact format:`, '{"translations":["item 1","item 2"]}',"Keep exactly the same number and order of items.","Translate every natural-language fragment completely into the target language. Never mix languages.","Preserve punctuation, line breaks, numbers, prices, URLs, email addresses, phone numbers, HTML entities and emoji.","Never translate these official names: PETS & DOGUE, DOGUE, DOGUE Trust, DOGUE Verified, Miso.","Do not add markdown, comments or explanations."].join("\n");try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,instructions,input:JSON.stringify({texts})})});const data=await r.json();if(!r.ok)return json(res,r.status,{error:data?.error?.message||"OpenAI translation request failed."});return json(res,200,{translations:parse(output(data),texts.length),targetLanguage:target})}catch(e){console.error("Translation endpoint error",e);return json(res,500,{error:e?.message||"Translation failed."})}}
